ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER DW_ECOMMERCE_BRASIL1
IDENTIFIED BY DW_ECOMMERCE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;

GRANT CONNECT TO DW_ECOMMERCE_BRASIL;
GRANT RESOURCE TO DW_ECOMMERCE_BRASIL;
GRANT UNLIMITED TABLESPACE TO DW_ECOMMERCE_BRASIL;
ALTER USER DW_ECOMMERCE_BRASIL DEFAULT ROLE ALL;